export const MAPS = Object.freeze({
    "Abducted Avenue" : "L_037_UFO2",
    "Abduction Avenue" : "level28_ufo",
    "Acid Pool" : "L_049_AcidPool",
    "Barbie Dream Dash" : "IPL_031_Plastic",
    "Blaster Base" : "level27_orange",
    "Blaster Base Zero" : "IPL_034_OrangeGravity",
    "Block Dash" : "level19_block",
    "Block Dash Endless" : "eventlevel8_block_endless",
    "Block Dash Legendary" : "eventlevel13_block_legendary",
    "Bombardment" : "level12_bomb",
    "Bot Bash" : "level22_bot",
    "Bucket Mayhem" : "IPL_041_Cheese3",
    "Burrito Bonanza" : "level29_rollingtowers",
    "Cannon Climb" : "level6_hill",
    "Cannonball Chaos" : "eventlevel9_cannonchaos",
    "Crab's Landing" : "L_035_beachCarnival",
    "Don't Be Jelly!" : "IPL_039_Cheese1",
    "Elimination Base" : "IPL_033_OrangeDM",
    "Floor Flip" : "level9_seesaw",
    "Honey Drop" : "level8_honey",
    "Hot Wheels Hustle" : "level23_wheels",
    "Hot Wheels Yeti Run" : "IPL_047_Flame",
    "Humble Stumble" : "level4_pushy",
    "Ice Caramba" : "SSL_016_IceSki",
    "Icy Heights" : "level3_ice",
    "Jungle Roll" : "level18_jungle",
    "Laser Dash" : "eventlevel1_dash",
    "Laser Tracer" : "level15_laser",
    "Lava Land" : "level21_pillar",
    "Lava Rush" : "level11_lava",
    "Lost Temple" : "level16_temple",
    "Monopoly Rush" : "IPL_038_Capital",
    "MrBeast's Dangerous Traps" : "IPL_044_Coconut",
    "MrBeast's Warehouse" : "level32_mall",
    "NFL Scramble" : "level6_hill_nfl",
    "Over & Under" : "level7_moving",
    "Pac-Man Power" : "IPL_050_Pizza",
    "Paint Splash" : "level20_paint",
    "Pivot Push" : "level5_pivot",
    "Rush Hour" : "level24_streamtiles",
    "Scaffold Stumble" : "L_036_purple",
    "sh-ARRRRGH-ks!" : "SSL_011_SharkPirate",
    "Sharkmuda Triangle" : "SSL_014_Sharktanic",
    "SkyRocket Royale" : "eventlevel12_collectionRocket",
    "Space Droooooop" : "eventlevel4_honeylg_hard",
    "Space Drooop" : "eventlevel3_honeylg_medium",
    "Space Drop" : "eventlevel2_honeylg_easy",
    "Space Race" : "level13_gravity",
    "Spin Go Round" : "level1_whirly",
    "Stumble Cove" : "level30_Jumping",
    "Stumble Trouble" : "eventlevel10_terrortumble",
    "Stumble Up" : "SSL_017_Vertigo",
    "Stumble Up EZ" : "SSL_017_Vertigo_Easy",
    "Super Lava Slide" : "eventlevel6_lavasl",
    "Super Paint Slide" : "eventlevel5_paintsl",
    "Super Pivot Slide" : "eventlevel7_pivotsl",
    "Super Slide" : "level14_slide",
    "Super Waterpark" : "SSL_015_slides",
    "Tetris Tumble" : "IPL_048_Protractor",
    "The Other Side" : "L_042_Chicken",
    "Tile Fall" : "level2_tile",
    "Treasure Island" : "level25_collectcarrots",
    "Turbo Temple" : "level26_JungleTemple",
    "UFOMG!" : "L_43_UFO3",
});

  export const EMOTES = Object.freeze({
    "Only Punch & Kick" : -3,
    "Hug Only" : -5,
    "Banana Only" : -4,
    "Punch Only" : -2,
    "Special Emotes" : -1,
    "Hug" : 8,
    "Punch" : 9,
    "Kick" : 13,
    "Banana" : 55,
    "Fire Punch" : 85,
    "Invisibility" : 174,
    "MrBeast Case" : 155,
    "Ball" : 156,
    "Golden Banana" : 122,
    "Wet Kick" : 123,
    "Charged Hug" : 124,
});   